
name: Simplest Workflow

on: 
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest      
    steps:
      #just logging stuff for fun
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      #Check out code 
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      
      #Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' 

      #Execute Python Script
      - name: Execute Python Script
        run: python my_script.py >> $GITHUB_STEP_SUMMARY

      - name: greeting
        run: echo "## Hi Everyone" >> $GITHUB_STEP_SUMMARY
      - run: echo "ğŸ This job's status is ${{ job.status }}."