
name: Simplest Workflow

on: 
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest      
    steps:
      #Check out code 
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      
      #Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' 

      #Write greeting on step summary page
      - name: Greeting
        run: echo "## Here are the word counts for each markdown file:" >> $GITHUB_STEP_SUMMARY

      #Execute Python script
      - name: Execute Python Script
        run: python hello_world.py >> $GITHUB_STEP_SUMMARY
      - run: echo "ğŸ This job's status is ${{ job.status }}."